# Generated by Django 5.0.2 on 2025-05-15 08:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_menu_menuitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="longitude",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="address",
            field=models.CharField(default="Adresse temporaire", max_length=255),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="siret",
            field=models.CharField(
                default="12345678912345",
                help_text="Numéro SIRET à 14 chiffres",
                max_length=14,
                unique=True,
                validators=[api.models.validate_siret],
            ),
        ),
    ]
