# Generated by Django 5.0.2 on 2025-05-15 09:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_restaurant_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="siret",
            field=models.CharField(
                help_text="Numéro SIRET à 14 chiffres",
                max_length=14,
                unique=True,
                validators=[api.models.validate_siret],
            ),
        ),
    ]
