# Generated by Django 5.0.2 on 2025-05-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_restaurant_siret"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="name",
            field=models.CharField(default="Menu par default", max_length=100),
            preserve_default=False,
        ),
    ]
