# Generated by Django 5.0.2 on 2025-05-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurateurprofile",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
