# Generated by Django 5.0.2 on 2025-06-03 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_restaurateurprofile_stripe_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="disponible",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Plat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plats",
                        to="api.menu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifiant", models.CharField(max_length=50, unique=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.restaurant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="api.order",
                    ),
                ),
                (
                    "plat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.plat"
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "plat")},
            },
        ),
    ]
