# Generated by Django 5.0.2 on 2025-06-06 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_menu_disponible_plat_table_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="plat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.menuitem"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu",
                to="api.restaurant",
            ),
        ),
        migrations.DeleteModel(
            name="Plat",
        ),
    ]
