# Generated by Django 5.0.2 on 2025-06-07 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_order_restaurant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="plat",
            new_name="menu_item",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="quantite",
            new_name="quantity",
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "menu_item")},
        ),
    ]
