# Generated by Django 5.0.2 on 2025-06-07 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_rename_plat_orderitem_menu_item_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="table_number",
        ),
    ]
