# Generated by Django 5.0.2 on 2025-06-07 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_remove_order_table_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
    ]
