# Generated by Django 5.0.2 on 2025-06-10 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_order_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="menu_item",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="api.table",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "name")},
        ),
    ]
