# Generated by Django 5.0.2 on 2025-06-10 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_rename_menu_item_orderitem_name_alter_order_table_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="name",
            new_name="menu_item",
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "menu_item")},
        ),
    ]
