# Generated by Django 5.0.2 on 2025-06-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_rename_name_orderitem_menu_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="owner_restaurateur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurants_temp",
                to="api.restaurateurprofile",
            ),
        ),
    ]
