# Generated by Django 5.0.2 on 2025-06-11 09:34

from django.db import migrations

def migrate_restaurant_owner(apps, schema_editor):
    Restaurant = apps.get_model('api', 'Restaurant')
    RestaurateurProfile = apps.get_model('api', 'RestaurateurProfile')
    User = apps.get_model('auth', 'User')

    for restaurant in Restaurant.objects.all():
        try:
            user = User.objects.get(id=restaurant.owner_id)
            restaurateur = RestaurateurProfile.objects.get(user=user)
            restaurant.owner_restaurateur = restaurateur
            restaurant.save()
        except RestaurateurProfile.DoesNotExist:
            print(f"[WARN] Aucun RestaurateurProfile pour user_id={user.id}")
        except User.DoesNotExist:
            print(f"[WARN] User id={restaurant.owner_id} inexistant")

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_restaurant_owner_restaurateur'),
    ]

    operations = [
        migrations.RunPython(migrate_restaurant_owner),
    ]
