# Generated by Django 5.0.2 on 2025-06-11 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_auto_20250611_1134"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="owner_restaurateur",
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurants",
                to="api.restaurateurprofile",
            ),
        ),
    ]
