# Generated by Django 5.0.2 on 2025-07-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_restaurateurprofile_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurateurprofile',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='restaurateurprofile',
            name='kbis',
        ),
    ]
