# Generated by Django 5.0.2 on 2025-07-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_restaurateurprofile_id_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_stripe_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurateurprofile',
            name='stripe_account_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurateurprofile',
            name='stripe_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
