# Generated by Django 5.0.2 on 2025-07-24 05:33

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_restaurant_is_stripe_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='Paris', max_length=100, verbose_name='Ville'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=models.CharField(default='France', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('french', 'Française'), ('italian', 'Italienne'), ('asian', 'Asiatique'), ('mexican', 'Mexicaine'), ('indian', 'Indienne'), ('american', 'Américaine'), ('mediterranean', 'Méditerranéenne'), ('japanese', 'Japonaise'), ('chinese', 'Chinoise'), ('thai', 'Thaïlandaise'), ('other', 'Autre')], default='french', max_length=50, verbose_name='Type de cuisine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254, verbose_name='Email de contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/%Y/%m/', verbose_name='Photo du restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Restaurant actif'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(default=33123456789, max_length=20, validators=[api.models.validate_phone], verbose_name='Téléphone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_range',
            field=models.IntegerField(choices=[(1, '€'), (2, '€€'), (3, '€€€'), (4, '€€€€')], default=2, verbose_name='Gamme de prix'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Note moyenne'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name="Nombre d'avis"),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='zip_code',
            field=models.CharField(default=75001, max_length=10, verbose_name='Code postal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_stripe_active',
            field=models.BooleanField(default=False, verbose_name='Paiements Stripe actifs'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='api.restaurateurprofile', verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='siret',
            field=models.CharField(help_text='Numéro SIRET à 14 chiffres', max_length=14, unique=True, validators=[api.models.validate_siret], verbose_name='SIRET'),
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fermé ce jour')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='api.restaurant')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('restaurant', 'day_of_week')},
            },
        ),
    ]
