# Generated by Django 5.0.2 on 2025-07-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_restaurant_options_restaurant_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Plat', 'verbose_name_plural': 'Plats'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.JSONField(blank=True, default=list, help_text='Liste des allergènes présents'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_gluten_free',
            field=models.BooleanField(default=False, verbose_name='Sans gluten'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_vegan',
            field=models.BooleanField(default=False, verbose_name='Vegan'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_vegetarian',
            field=models.BooleanField(default=False, verbose_name='Végétarien'),
        ),
    ]
