# Generated by Django 5.0.2 on 2025-07-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_menuitem_options_menuitem_allergens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='accepts_meal_vouchers',
            field=models.BooleanField(default=False, help_text='Indique si le restaurant accepte les titres-restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='meal_voucher_info',
            field=models.TextField(blank=True, help_text='Informations supplémentaires sur les titres-restaurant acceptés (ex: types, conditions)', null=True),
        ),
    ]
