# Generated by Django 5.0.2 on 2025-07-31 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_order_options_alter_orderitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('restaurant', 'number')},
        ),
    ]
