# Generated by Django 5.0.2 on 2025-08-08 15:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_table_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['restaurant', 'number'], 'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.AddField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=4, help_text='Nombre de personnes que peut accueillir la table', verbose_name='Capacité'),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si la table peut recevoir des commandes', verbose_name='Table active'),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.CharField(help_text='Numéro affiché sur la table (ex: 1, 2, A1, etc.)', max_length=10, verbose_name='Numéro de table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='qr_code',
            field=models.CharField(blank=True, help_text='Identifiant unique pour le QR code (généré automatiquement)', max_length=100, null=True, unique=True, verbose_name='Code QR'),
        ),
        migrations.AlterField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='api.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['restaurant', 'is_active'], name='api_table_restaur_235adb_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['qr_code'], name='api_table_qr_code_c8e42d_idx'),
        ),
    ]
