# Generated by Django 5.0.2 on 2025-08-16 13:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_order_guest_contact_name_order_guest_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantHoursTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('traditional', 'Restaurant traditionnel'), ('brasserie', 'Brasserie/Bistrot'), ('fast_food', 'Restauration rapide'), ('gastronomic', 'Restaurant gastronomique'), ('cafe', 'Café'), ('bar', 'Bar'), ('custom', 'Personnalisé')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('hours_data', models.JSONField(help_text='Structure: [{dayOfWeek: 0, isClosed: false, periods: [...]}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Template d'horaires",
                'verbose_name_plural': "Templates d'horaires",
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='openinghours',
            options={'ordering': ['day_of_week'], 'verbose_name': "Horaires d'ouverture", 'verbose_name_plural': "Horaires d'ouverture"},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_manually_overridden',
            field=models.BooleanField(default=False, verbose_name='Fermeture manuelle active'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='last_status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière modification le'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='last_status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Dernière modification par'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='manual_override_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Raison de la fermeture manuelle'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='manual_override_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fermeture manuelle jusqu'à"),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Dimanche'), (1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')]),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OpeningPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name="Heure d'ouverture")),
                ('end_time', models.TimeField(verbose_name='Heure de fermeture')),
                ('name', models.CharField(blank=True, help_text='Nom du service (ex: Service midi, Service soir)', max_length=100, null=True)),
                ('opening_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='api.openinghours')),
            ],
            options={
                'verbose_name': "Période d'ouverture",
                'verbose_name_plural': "Périodes d'ouverture",
                'ordering': ['start_time'],
            },
        ),
    ]
