# Generated by Django 5.0.2 on 2025-08-22 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_restauranthourstemplate_alter_openinghours_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_number', models.CharField(max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('primary_customer_name', models.CharField(blank=True, max_length=100)),
                ('primary_phone', models.CharField(blank=True, max_length=20)),
                ('guest_count', models.PositiveIntegerField(default=1)),
                ('session_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='is_main_order',
            field=models.BooleanField(default=True, help_text='Première commande de la session de table'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_sequence',
            field=models.PositiveIntegerField(default=1, help_text='Numéro de séquence pour cette table/session'),
        ),
        migrations.AddField(
            model_name='order',
            name='table_session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifie une session de table pour regrouper les commandes'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='manual_override_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fermeture manuelle jusqu'à "),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'table_number', 'status'], name='api_order_restaur_8fe499_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['table_session_id'], name='api_order_table_s_1f5a69_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'created_at'], name='api_order_restaur_e3f7d3_idx'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant'),
        ),
        migrations.AddIndex(
            model_name='tablesession',
            index=models.Index(fields=['restaurant', 'table_number', 'is_active'], name='api_tablese_restaur_ea9e70_idx'),
        ),
    ]
