# Generated by Django 5.0.2 on 2025-08-25 13:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_tablesession_order_is_main_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Calories (pour 100g)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='preparation_time',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Temps de préparation (minutes)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock_alert_threshold',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Seuil d'alerte stock"),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité en stock'),
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Emoji représentant la catégorie (ex: 🥗, 🍽️, 🍰)', max_length=10, null=True, verbose_name='Icône emoji')),
                ('color', models.CharField(default='#1E2A78', help_text='Code couleur hexadécimal (ex: #1E2A78)', max_length=7, verbose_name='Couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='api.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Catégorie de menu',
                'verbose_name_plural': 'Catégories de menu',
                'ordering': ['restaurant', 'order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.menucategory', verbose_name='Catégorie'),
        ),
        migrations.CreateModel(
            name='MenuSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la sous-catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.menucategory', verbose_name='Catégorie parent')),
            ],
            options={
                'verbose_name': 'Sous-catégorie de menu',
                'verbose_name_plural': 'Sous-catégories de menu',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='api.menusubcategory', verbose_name='Sous-catégorie'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['restaurant', 'is_active'], name='api_menucat_restaur_0d4cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['restaurant', 'order'], name='api_menucat_restaur_b756e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menucategory',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AddIndex(
            model_name='menusubcategory',
            index=models.Index(fields=['category', 'is_active'], name='api_menusub_categor_6a3289_idx'),
        ),
        migrations.AddIndex(
            model_name='menusubcategory',
            index=models.Index(fields=['category', 'order'], name='api_menusub_categor_4b9701_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menusubcategory',
            unique_together={('category', 'name')},
        ),
    ]
