# Generated by Django 5.0.2 on 2025-09-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_menuitem_calories_menuitem_preparation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/%Y/%m/', verbose_name='Photo du plat'),
        ),
    ]
