# Generated by Django 5.0.2 on 2025-09-09 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_menuitem_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date pour laquelle ce menu du jour est valide', verbose_name='Date du menu')),
                ('is_active', models.BooleanField(default=True, help_text="Si False, le menu du jour n'apparaît pas côté client", verbose_name='Menu actif')),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, help_text="Prix spécial pour l'ensemble du menu (optionnel)", max_digits=8, null=True, verbose_name='Prix menu complet')),
                ('title', models.CharField(default='Menu du Jour', max_length=200, verbose_name='Titre du menu')),
                ('description', models.TextField(blank=True, help_text='Description ou note spéciale pour ce menu', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to='api.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Menu du jour',
                'verbose_name_plural': 'Menus du jour',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyMenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=True, verbose_name="Disponible aujourd'hui")),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix pour ce jour (si différent du prix normal)', max_digits=8, null=True, verbose_name='Prix spécial')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('special_note', models.CharField(blank=True, help_text="Note visible côté client (ex: 'Fait maison', 'Produit frais du jour')", max_length=200, null=True, verbose_name='Note spéciale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menu_items', to='api.dailymenu', verbose_name='Menu du jour')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menu_appearances', to='api.menuitem', verbose_name='Plat')),
            ],
            options={
                'verbose_name': 'Plat du menu du jour',
                'verbose_name_plural': 'Plats des menus du jour',
                'ordering': ['daily_menu__date', 'display_order', 'menu_item__category__order'],
            },
        ),
        migrations.CreateModel(
            name='DailyMenuTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Template actif')),
                ('day_of_week', models.PositiveIntegerField(blank=True, choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], help_text='Si défini, ce template sera suggéré pour ce jour', null=True, verbose_name='Jour de la semaine')),
                ('default_special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix menu par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Dernière utilisation')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menu_templates', to='api.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Template de menu du jour',
                'verbose_name_plural': 'Templates de menus du jour',
                'ordering': ['restaurant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyMenuTemplateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix spécial par défaut')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('default_note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Note par défaut')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menuitem', verbose_name='Plat')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_items', to='api.dailymenutemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Plat de template',
                'verbose_name_plural': 'Plats de templates',
                'ordering': ['template', 'display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='dailymenu',
            index=models.Index(fields=['restaurant', 'date'], name='api_dailyme_restaur_7bbf22_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymenu',
            index=models.Index(fields=['restaurant', 'is_active'], name='api_dailyme_restaur_f09b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymenu',
            index=models.Index(fields=['date', 'is_active'], name='api_dailyme_date_532d7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymenu',
            unique_together={('restaurant', 'date')},
        ),
        migrations.AddIndex(
            model_name='dailymenuitem',
            index=models.Index(fields=['daily_menu', 'is_available'], name='api_dailyme_daily_m_0330be_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymenuitem',
            index=models.Index(fields=['daily_menu', 'display_order'], name='api_dailyme_daily_m_ccb254_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymenuitem',
            unique_together={('daily_menu', 'menu_item')},
        ),
        migrations.AlterUniqueTogether(
            name='dailymenutemplate',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='dailymenutemplateitem',
            unique_together={('template', 'menu_item')},
        ),
    ]
