# Generated by Django 5.0.2 on 2025-09-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_order_is_split_payment_alter_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='vat_category',
            field=models.CharField(choices=[('FOOD', 'Aliments (sur place ou à emporter)'), ('DRINK_SOFT', 'Boissons sans alcool'), ('DRINK_ALCOHOL', 'Boissons alcoolisées'), ('PACKAGED', 'Produits préemballés')], default='FOOD', max_length=20, verbose_name='Catégorie TVA'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=3, default=0.1, help_text='Taux de TVA applicable (ex: 0.10 pour 10%)', max_digits=4, verbose_name='Taux de TVA'),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_details',
            field=models.JSONField(blank=True, default=dict, help_text='{"10": {"ht": 45.45, "tva": 4.55, "ttc": 50}, ...}', verbose_name='Détail TVA par taux'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant TVA'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=3, default=0.1, max_digits=4, verbose_name='Taux de TVA appliqué'),
        ),
    ]
