# Generated by Django 5.0.2 on 2025-09-27 09:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_orderitem_options_phoneverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('client', 'Client'), ('restaurateur', 'Restaurateur')], max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('siret', models.CharField(blank=True, max_length=14, null=True)),
                ('verification_code', models.CharField(max_length=6)),
                ('code_sent_at', models.DateTimeField(auto_now_add=True)),
                ('last_resend_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'verification_code'], name='api_pending_email_71e1fb_idx'), models.Index(fields=['telephone', 'is_verified'], name='api_pending_telepho_c34af4_idx'), models.Index(fields=['created_at'], name='api_pending_created_35bb7a_idx')],
            },
        ),
    ]
