# Generated by Django 5.0.2 on 2025-10-22 08:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_accountdeletionrequest_legalconsent_dataaccesslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_visible_to_session',
            field=models.BooleanField(default=True, verbose_name='Visible par la session'),
        ),
        migrations.CreateModel(
            name='CollaborativeTableSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_code', models.CharField(db_index=True, max_length=6, unique=True, verbose_name='Code de partage')),
                ('table_number', models.CharField(max_length=10)),
                ('session_type', models.CharField(choices=[('collaborative', 'Collaborative'), ('individual', 'Individuelle')], default='collaborative', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('locked', 'Verrouillée'), ('payment', 'En paiement'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='active', max_length=20)),
                ('host_name', models.CharField(blank=True, max_length=100, verbose_name="Nom de l'hôte")),
                ('max_participants', models.PositiveIntegerField(default=10, verbose_name='Nombre max de participants')),
                ('require_approval', models.BooleanField(default=False, verbose_name='Approbation requise pour rejoindre')),
                ('allow_join_after_lock', models.BooleanField(default=False, verbose_name='Autoriser à rejoindre après verrouillage')),
                ('split_payment_enabled', models.BooleanField(default=True, verbose_name='Paiement divisé activé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session_notes', models.TextField(blank=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Hôte')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborative_sessions', to='api.restaurant')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborative_sessions', to='api.table')),
            ],
            options={
                'db_table': 'collaborative_table_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='collaborative_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.collaborativetablesession', verbose_name='Session collaborative'),
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(blank=True, max_length=100, verbose_name='Nom (invité)')),
                ('guest_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone (invité)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('left', 'Parti'), ('removed', 'Retiré')], default='active', max_length=20)),
                ('role', models.CharField(choices=[('host', 'Hôte'), ('member', 'Membre')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.collaborativetablesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_participants',
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.sessionparticipant', verbose_name='Participant'),
        ),
        migrations.AddIndex(
            model_name='collaborativetablesession',
            index=models.Index(fields=['share_code'], name='collaborati_share_c_70f444_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborativetablesession',
            index=models.Index(fields=['restaurant', 'status'], name='collaborati_restaur_a68a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborativetablesession',
            index=models.Index(fields=['table', 'status'], name='collaborati_table_i_b90be3_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionparticipant',
            index=models.Index(fields=['session', 'status'], name='session_par_session_299472_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionparticipant',
            unique_together={('session', 'user')},
        ),
    ]
