# Generated by Django 5.0.2 on 2025-10-23 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_order_is_visible_to_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborativetablesession',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text="Date et heure d'archivage de la session", null=True),
        ),
        migrations.AddField(
            model_name='collaborativetablesession',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Indique si la session est archivée (libère la table)'),
        ),
        migrations.AddIndex(
            model_name='collaborativetablesession',
            index=models.Index(fields=['table', 'is_archived', 'status'], name='collaborati_table_i_bc973f_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborativetablesession',
            index=models.Index(fields=['is_archived', 'archived_at'], name='collaborati_is_arch_a97d4c_idx'),
        ),
    ]
