# Generated by Django 5.0.2 on 2025-11-05 07:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_collaborativetablesession_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComptabiliteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(default='FACT', help_text='Préfixe des numéros de facture', max_length=10)),
                ('last_invoice_number', models.PositiveIntegerField(default=0)),
                ('invoice_year_reset', models.BooleanField(default=True, help_text='Réinitialiser la numérotation chaque année')),
                ('tva_regime', models.CharField(choices=[('normal', 'Régime normal'), ('simplifie', 'Régime simplifié'), ('franchise', 'Franchise TVA')], default='normal', max_length=20)),
                ('export_format_default', models.CharField(choices=[('FEC', 'Format FEC'), ('CSV', 'Format CSV'), ('PDF', 'Format PDF')], default='FEC', max_length=10)),
                ('siret', models.CharField(blank=True, max_length=14)),
                ('tva_intracommunautaire', models.CharField(blank=True, max_length=20)),
                ('code_naf', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comptabilite_settings', to='api.restaurateurprofile')),
            ],
            options={
                'verbose_name': 'Configuration comptable',
                'db_table': 'comptabilite_settings',
            },
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_code', models.CharField(default='VE', max_length=10)),
                ('ecriture_num', models.CharField(max_length=20, unique=True)),
                ('ecriture_date', models.DateField()),
                ('compte_num', models.CharField(max_length=20)),
                ('compte_lib', models.CharField(max_length=255)),
                ('piece_ref', models.CharField(max_length=50)),
                ('piece_date', models.DateField()),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ecriture_lib', models.CharField(max_length=255)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=100)),
                ('tva_taux', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.order')),
                ('restaurateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures_comptables', to='api.restaurateurprofile')),
            ],
            options={
                'db_table': 'ecritures_comptables',
                'ordering': ['ecriture_date', 'ecriture_num'],
                'indexes': [models.Index(fields=['restaurateur', 'ecriture_date'], name='ecritures_c_restaur_6b5815_idx'), models.Index(fields=['piece_ref'], name='ecritures_c_piece_r_85967a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExportComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_export', models.CharField(choices=[('FEC', 'Fichier FEC'), ('CSV', 'Export CSV'), ('PDF', 'Rapport PDF'), ('TVA', 'Déclaration TVA'), ('RECETTES', 'Livre de recettes')], max_length=20)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('fichier_url', models.URLField(blank=True, max_length=500)),
                ('fichier_nom', models.CharField(max_length=255)),
                ('fichier_taille', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('complete', 'Complété'), ('erreur', 'Erreur')], default='en_cours', max_length=20)),
                ('message_erreur', models.TextField(blank=True)),
                ('nombre_lignes', models.PositiveIntegerField(default=0)),
                ('checksum_md5', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text="Date d'expiration du lien de téléchargement", null=True)),
                ('restaurateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports_comptables', to='api.restaurateurprofile')),
            ],
            options={
                'db_table': 'exports_comptables',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurateur', 'created_at'], name='exports_com_restaur_0a11aa_idx'), models.Index(fields=['type_export', 'statut'], name='exports_com_type_ex_a4272e_idx')],
            },
        ),
        migrations.CreateModel(
            name='FactureSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('restaurateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facture_sequences', to='api.restaurateurprofile')),
            ],
            options={
                'db_table': 'facture_sequences',
                'indexes': [models.Index(fields=['restaurateur', 'year', 'month'], name='facture_seq_restaur_c2baec_idx')],
                'unique_together': {('restaurateur', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='RecapitulatifTVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('ca_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ca_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tva_5_5_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tva_5_5_montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tva_10_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tva_10_montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tva_20_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tva_20_montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tva_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('nombre_factures', models.PositiveIntegerField(default=0)),
                ('ticket_moyen', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('commissions_stripe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('virements_stripe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recapitulatifs_tva', to='api.restaurateurprofile')),
            ],
            options={
                'db_table': 'recapitulatifs_tva',
                'indexes': [models.Index(fields=['restaurateur', 'year', 'month'], name='recapitulat_restaur_c1c90a_idx')],
                'unique_together': {('restaurateur', 'year', 'month')},
            },
        ),
    ]
