# Generated by Django 5.0.2 on 2025-12-11 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_comptabilitesettings_ecriturecomptable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_updates', models.BooleanField(default=True, help_text='Mises à jour des commandes')),
                ('order_ready', models.BooleanField(default=True, help_text='Commande prête')),
                ('payment_received', models.BooleanField(default=True, help_text='Paiement reçu')),
                ('new_orders', models.BooleanField(default=True, help_text='Nouvelles commandes (restaurateurs)')),
                ('promotions', models.BooleanField(default=False, help_text='Offres promotionnelles')),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, default='22:00', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, default='08:00', null=True)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('vibration_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférences de notification',
                'verbose_name_plural': 'Préférences de notification',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('notification_type', models.CharField(choices=[('order_created', 'Commande créée'), ('order_confirmed', 'Commande confirmée'), ('order_preparing', 'Commande en préparation'), ('order_ready', 'Commande prête'), ('order_served', 'Commande servie'), ('order_cancelled', 'Commande annulée'), ('payment_received', 'Paiement reçu'), ('payment_failed', 'Échec de paiement'), ('split_payment_update', 'Mise à jour paiement divisé'), ('session_joined', 'Participant rejoint'), ('session_left', 'Participant parti'), ('promotion', 'Promotion'), ('system', 'Système')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('restaurant_id', models.IntegerField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('critical', 'Critique')], default='normal', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('push_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['order_id'], name='notificatio_order_i_25eb33_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushNotificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expo_token', models.CharField(max_length=255, unique=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('device_platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], default='android', max_length=20)),
                ('guest_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de notification push',
                'verbose_name_plural': 'Tokens de notification push',
                'db_table': 'push_notification_tokens',
                'indexes': [models.Index(fields=['user', 'is_active'], name='push_notifi_user_id_f139ae_idx'), models.Index(fields=['expo_token'], name='push_notifi_expo_to_8aa8d4_idx'), models.Index(fields=['guest_phone'], name='push_notifi_guest_p_f68aa6_idx')],
            },
        ),
    ]
