# Generated by Django 5.0.2 on 2026-02-02 08:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_notificationpreferences_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreferences',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, default=datetime.time(22, 0), null=True),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Utilisateur associé (optionnel pour vérification pré-inscription)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='phoneverification',
            index=models.Index(fields=['phone_number', 'is_verified'], name='api_phoneve_phone_n_e9f29a_idx'),
        ),
    ]
