# Generated by Django 5.0.2 on 2026-02-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_notificationpreferences_quiet_hours_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
