# Generated by Django 5.0.2 on 2026-02-26 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_clientprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('special_instructions', models.TextField(blank=True)),
                ('customizations', models.JSONField(blank=True, default=dict)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_cart_items', to='api.menuitem')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.sessionparticipant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.collaborativetablesession')),
            ],
            options={
                'ordering': ['added_at'],
                'indexes': [models.Index(fields=['session', 'participant'], name='api_session_session_6c10b4_idx')],
            },
        ),
    ]
