# Generated by Django 5.0.2 on 2026-03-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_emailverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_access_token',
            field=models.CharField(blank=True, default='', help_text="Token opaque pour accès invité aux endpoints reçu (secrets.token_urlsafe(32)). Généré automatiquement à la création d'une commande guest (source='guest' ou user=None).", max_length=64),
        ),
    ]
