# Generated by Django 5.0.2 on 2026-03-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_order_guest_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='raison_sociale',
            field=models.CharField(blank=True, default='', help_text="Raison sociale de l'établissement", max_length=200, verbose_name='Raison sociale'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
