# Generated by Django 5.0.2 on 2026-04-10 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_restaurant_raison_sociale_alter_menu_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitpaymentportion',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_portions', to='api.sessionparticipant'),
        ),
    ]
