# Generated by Django 5.0.2 on 2026-05-26 12:51

import api.models.ai_menu_models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_passwordresetcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text="Traductions par code langue : {'en': {'name': ..., 'description': ...}}. Le français est porté par les champs natifs.", verbose_name='Traductions'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text="Traductions par code langue : {'en': {'name': ..., 'description': ...}}. Le français est porté par les champs natifs.", verbose_name='Traductions'),
        ),
        migrations.AddField(
            model_name='menusubcategory',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text="Traductions par code langue : {'en': {'name': ..., 'description': ...}}. Le français est porté par les champs natifs.", verbose_name='Traductions'),
        ),
        migrations.CreateModel(
            name='MenuScanJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', "Analyse de l'image"), ('translating', 'Traduction en cours'), ('ready', 'Prêt à valider'), ('applied', 'Appliqué au menu'), ('failed', 'Échec')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('target_languages', models.JSONField(blank=True, default=api.models.ai_menu_models.default_target_languages, help_text='Codes ISO des langues cibles pour la traduction (hors français).', verbose_name='Langues cibles')),
                ('extracted_data', models.JSONField(blank=True, default=dict, verbose_name='Données extraites (brouillon)')),
                ('branding_data', models.JSONField(blank=True, default=dict, verbose_name='Charte graphique détectée')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Réponse brute du modèle')),
                ('error_message', models.TextField(blank=True, default='', verbose_name="Message d'erreur")),
                ('model_used', models.CharField(blank=True, default='', max_length=80)),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_scan_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_scan_jobs', to='api.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Import de menu (IA)',
                'verbose_name_plural': 'Imports de menu (IA)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuScanImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=api.models.ai_menu_models.menu_scan_image_path, verbose_name='Photo de la carte')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre de la page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.menuscanjob', verbose_name="Job d'import")),
            ],
            options={
                'verbose_name': 'Photo de carte',
                'verbose_name_plural': 'Photos de carte',
                'ordering': ['job', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_color', models.CharField(default='#1E2A78', max_length=7, verbose_name='Couleur principale')),
                ('secondary_color', models.CharField(default='#D4AF37', max_length=7, verbose_name='Couleur secondaire')),
                ('accent_color', models.CharField(default='#2938A3', max_length=7, verbose_name="Couleur d'accent")),
                ('background_color', models.CharField(default='#F9FAFB', max_length=7, verbose_name='Couleur de fond')),
                ('text_color', models.CharField(default='#111827', max_length=7, verbose_name='Couleur du texte')),
                ('style_descriptor', models.CharField(blank=True, default='', help_text='Ambiance détectée (ex: « élégant », « bistrot chaleureux »).', max_length=120, verbose_name='Style')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name="Générée par l'IA")),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='api.restaurant', verbose_name='Restaurant')),
                ('source_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branding_results', to='api.menuscanjob', verbose_name="Job d'origine")),
            ],
            options={
                'verbose_name': 'Charte graphique de restaurant',
                'verbose_name_plural': 'Chartes graphiques de restaurant',
            },
        ),
        migrations.AddIndex(
            model_name='menuscanjob',
            index=models.Index(fields=['restaurant', 'status'], name='api_menusca_restaur_82df83_idx'),
        ),
        migrations.AddIndex(
            model_name='menuscanjob',
            index=models.Index(fields=['status', 'created_at'], name='api_menusca_status_69dc62_idx'),
        ),
        migrations.AddIndex(
            model_name='menuscanimage',
            index=models.Index(fields=['job', 'order'], name='api_menusca_job_id_bb21bb_idx'),
        ),
    ]
