# Generated by Django 5.0.2 on 2026-05-28 16:11

import api.models.ai_menu_models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_menucategory_translations_menuitem_translations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menuscanjob',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_scan_jobs', to='api.menu', verbose_name='Menu cible'),
        ),
        migrations.CreateModel(
            name='MenuTranslationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'Traduction en cours'), ('done', 'Terminé'), ('failed', 'Échec')], db_index=True, default='pending', max_length=20)),
                ('target_languages', models.JSONField(blank=True, default=api.models.ai_menu_models.default_target_languages)),
                ('progress_done', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(default=0)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_translation_jobs', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_translation_jobs', to='api.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Traduction de menu (IA)',
                'verbose_name_plural': 'Traductions de menu (IA)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'status'], name='api_menutra_restaur_7fb7d8_idx')],
            },
        ),
    ]
