# Generated by Django 5.0.2 on 2026-05-31 17:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_menuscanjob_menu_menutranslationjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitpaymentsession',
            name='split_type',
            field=models.CharField(choices=[('equal', 'Équitable'), ('custom', 'Personnalisé'), ('items', 'Par article')], max_length=10),
        ),
        migrations.CreateModel(
            name='SplitPaymentItemClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_claims', to='api.orderitem')),
                ('portion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_claims', to='api.splitpaymentportion')),
            ],
            options={
                'db_table': 'split_payment_item_claims',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['order_item'], name='split_claim_item_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='splitpaymentitemclaim',
            constraint=models.UniqueConstraint(fields=('portion', 'order_item'), name='uniq_claim_portion_item'),
        ),
    ]
