# Generated by Django 5.0.2 on 2026-06-23 10:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_splitpaymentsession_split_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='kind',
            field=models.CharField(choices=[('dish', 'Plat à la carte'), ('formule', 'Formule')], default='dish', max_length=10, verbose_name='Type de ligne'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='label',
            field=models.CharField(blank=True, max_length=150, verbose_name='Libellé figé (formule)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.menuitem'),
        ),
        migrations.CreateModel(
            name='Formule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix unique payé par le client, réparti entre les crans.', max_digits=6, verbose_name='Prix total (TTC)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formules', to='api.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Formule',
                'verbose_name_plural': 'Formules',
                'ordering': ['restaurant', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='formule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='api.formule', verbose_name='Formule'),
        ),
        migrations.CreateModel(
            name='FormuleCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nom du cran')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_required', models.BooleanField(default=True, help_text='Si décoché, le client peut passer ce cran (ex. dessert optionnel).', verbose_name='Obligatoire')),
                ('min_choices', models.PositiveIntegerField(default=1, verbose_name='Choix minimum')),
                ('max_choices', models.PositiveIntegerField(default=1, verbose_name='Choix maximum')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.formule', verbose_name='Formule')),
            ],
            options={
                'verbose_name': 'Cran de formule',
                'verbose_name_plural': 'Crans de formule',
                'ordering': ['formule', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormuleCourseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extra_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Supplément ajouté au prix de la formule si ce plat est choisi.', max_digits=5, verbose_name='Supplément')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.formulecourse', verbose_name='Cran')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formule_appearances', to='api.menuitem', verbose_name='Plat')),
            ],
            options={
                'verbose_name': 'Plat de formule',
                'verbose_name_plural': 'Plats de formule',
                'ordering': ['course', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50, verbose_name='Cran')),
                ('menu_item_name', models.CharField(max_length=100)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('allocated_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=3, default=Decimal('0.100'), max_digits=4)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.menuitem')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='api.orderitem')),
            ],
            options={
                'verbose_name': 'Composant de formule',
                'verbose_name_plural': 'Composants de formule',
                'ordering': ['order_item', 'display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='formule',
            index=models.Index(fields=['restaurant', 'is_active'], name='api_formule_restaur_b55ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='formule',
            index=models.Index(fields=['restaurant', 'order'], name='api_formule_restaur_87a106_idx'),
        ),
        migrations.AddIndex(
            model_name='formulecourseitem',
            index=models.Index(fields=['course', 'is_available'], name='api_formule_course__f1767e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formulecourseitem',
            unique_together={('course', 'menu_item')},
        ),
    ]
