# Generated by Django 5.0.2 on 2026-06-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_orderitem_kind_orderitem_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftorder',
            name='formules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
