# Generated by Django 5.0.2 on 2026-07-03 08:33

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_draftorder_formules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vat_details',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='{"10": {"ht": 45.45, "tva": 4.55, "ttc": 50}, ...}', verbose_name='Détail TVA par taux'),
        ),
    ]
