# Generated by Django 5.0.2 on 2026-07-04 14:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_order_vat_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1-5)')),
                ('comment', models.TextField(blank=True, default='', max_length=2000, verbose_name='Commentaire')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.order', verbose_name='Commande liée')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Avis restaurant',
                'verbose_name_plural': 'Avis restaurants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'is_visible'], name='api_restaur_restaur_ea0b62_idx'), models.Index(fields=['restaurant', '-created_at'], name='api_restaur_restaur_d5d284_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='restaurantreview',
            constraint=models.UniqueConstraint(fields=('restaurant', 'client'), name='unique_review_per_client_restaurant'),
        ),
    ]
