# Generated by Django 5.0.2 on 2026-07-09 14:00

import api.models.table_occupancy_models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_restaurantreview_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='pos_x',
            field=models.FloatField(blank=True, help_text='Position X relative sur le plan (0..1). NULL = jamais placée', null=True, verbose_name='Position X'),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_y',
            field=models.FloatField(blank=True, help_text='Position Y relative sur le plan (0..1). NULL = jamais placée', null=True, verbose_name='Position Y'),
        ),
        migrations.AddField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('square', 'Carrée'), ('round', 'Ronde'), ('rect', 'Rectangle')], default='square', max_length=10, verbose_name='Forme'),
        ),
        migrations.AddField(
            model_name='table',
            name='zone',
            field=models.CharField(blank=True, help_text='Zone du restaurant (Salle, Terrasse, Étage...)', max_length=50, verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programmée'), ('pending', 'En Attente'), ('confirmed', 'Confirmée'), ('preparing', 'En Préparation'), ('ready', 'Prête'), ('served', 'Servie'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(help_text="starts_at + duration_minutes (dénormalisé pour les requêtes d'overlap)")),
                ('duration_minutes', models.PositiveSmallIntegerField(default=90)),
                ('party_size', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('pending_payment', 'En attente de paiement'), ('confirmed', 'Confirmée'), ('seated', 'Client installé'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('no_show', 'Non présenté'), ('expired', 'Expirée (paiement non finalisé)')], db_index=True, default='confirmed', max_length=20)),
                ('prep_lead_minutes', models.PositiveSmallIntegerField(default=15)),
                ('kitchen_fired_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Deadline de paiement pour pending_payment', null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('refund_id', models.CharField(blank=True, max_length=100)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pre_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='api.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.restaurant')),
                ('table', models.ForeignKey(blank=True, help_text='Table assignée automatiquement à la création', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='api.table')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['restaurant', 'starts_at', 'status'], name='api_reserva_restaur_3255ac_idx'), models.Index(fields=['table', 'starts_at'], name='api_reserva_table_i_0f9b18_idx'), models.Index(fields=['status', 'expires_at'], name='api_reserva_status_4ee9bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='TableOccupancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('manual', 'Manuel (staff)'), ('order', 'Commande app'), ('blocked', 'Table bloquée')], default='manual', max_length=10)),
                ('party_size', models.PositiveSmallIntegerField(default=2)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_end_at', models.DateTimeField(default=api.models.table_occupancy_models.default_expected_end)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_occupancies', to='api.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='api.table')),
            ],
            options={
                'verbose_name': 'Occupation de table',
                'verbose_name_plural': 'Occupations de tables',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['table', 'ended_at'], name='api_tableoc_table_i_9ac9c3_idx'), models.Index(fields=['restaurant', 'ended_at'], name='api_tableoc_restaur_967d79_idx')],
            },
        ),
    ]
