# Generated by Django 5.0.2 on 2026-07-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_table_pos_x_table_pos_y_table_shape_table_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='reservations_enabled',
            field=models.BooleanField(default=False, help_text='Permet aux clients de réserver une table (avec pré-commande prépayée optionnelle). Désactivé par défaut : à activer une fois les tables et horaires configurés.', verbose_name='Réservations en ligne activées'),
        ),
    ]
