# Generated by Django 5.0.2 on 2026-07-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_restaurant_reservations_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='reservation_preorders_enabled',
            field=models.BooleanField(default=True, help_text='Permet aux clients de commander et payer leur repas au moment de la réservation. Sans effet si les réservations sont désactivées.', verbose_name='Pré-commande prépayée activée'),
        ),
    ]
