# Generated by Django 5.0.2 on 2026-07-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_restaurant_reservation_preorders_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='capacity_max',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Capacité maximale avec rallonge pour les tables modulables (ex: carrée 4 places → rectangle 6 places). Vide = non modulable.', null=True, verbose_name='Capacité étendue'),
        ),
    ]
