# Generated by Django 5.0.2 on 2026-07-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_table_capacity_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='stripe_terminal_location_id',
            field=models.CharField(blank=True, default='', help_text="Créée à la volée. Vide tant qu'aucun encaissement sans contact n'a eu lieu.", max_length=255, verbose_name='Location Stripe Terminal'),
        ),
    ]
