version: '3.8'

services:

  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - ws-server

  ws-server:
    build:
      context: ./ws-server
    container_name: ws-server
    volumes:
      - ./ws-server:/app
    ports:
      - "4000:4000"

networks:
  default:
    driver: bridge