services:
  web:
    build: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    
  test:
    build: .
    command: pytest
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOST=*
      - DJANGO_CORS_ALLOW_ALL=True
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: eatandgo
      POSTGRES_USER: eatuser
      POSTGRES_PASSWORD: eatpass

volumes:
  postgres_data:
